### ISSUE TITLE
GNOME 44 support

### ISSUE THREAD

**Issue by yochananmarqos** [yilozt/rounded-window-corners#114]
I tried bumping the library versions (see diff) for GNOME 44.beta, but apparently there's more that needs to be done.

<details>
<summary>Diff</summary>

```
--- .gi.ts.rc-a.json	2023-02-28 08:27:27.571115735 -0700
+++ .gi.ts.rc-b.json	2023-02-28 08:37:19.859998594 -0700
@@ -35,9 +35,9 @@
     "For example, if you are using gnome 40, the version of Cogl should be 8.    "
   ],
   "libraries_ext": {
-    "Cogl":     [ "10" ],
-    "Clutter":  [ "10" ],
-    "Meta":     [ "10" ],
+    "Cogl":     [ "12" ],
+    "Clutter":  [ "12" ],
+    "Meta":     [ "12" ],
     "Shell":    [ "0.1" ],
     "GLib":     [ "2.0" ],
     "Gio":      [ "2.0" ],
@@ -62,10 +62,12 @@
   ],
   "xdg_data_dirs": {
     "ext": [
+      "/usr/lib64/mutter-12",
       "/usr/lib64/mutter-11",
       "/usr/lib64/mutter-10",
       "/usr/lib64/mutter-9",
       "/usr/lib64/mutter-8",
+      "/usr/lib/x86_64-linux-gnu/mutter-12",
       "/usr/lib/x86_64-linux-gnu/mutter-11",
       "/usr/lib/x86_64-linux-gnu/mutter-10",
       "/usr/lib/x86_64-linux-gnu/mutter-9",
@@ -79,4 +81,4 @@
       "/usr/local/share"
     ]
   }
-}
\ No newline at end of file
+}
```

</details>

<details>
<summary>Build log</summary>

```
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.15s.
yarn run v1.22.19
$ gulp build
[08:41:45] Using gulpfile /mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/gulpfile.js
[08:41:45] Starting 'build'...
[08:41:45] Starting '<anonymous>'...
[08:41:45] Finished '<anonymous>' after 1.52 ms
[08:41:45] Starting 'generate_gi_ext'...
[08:41:45] Starting 'generate_gi_prefs'...
Try to detect detect version of gnome-shell
Gnome-shell version:  12
Generate .d.ts files for preferences pages: 
Loading docs.json...
Finding GIR files...
Resolving libraries...
Loading GIR files...
Adding generics...
Injecting types...
Generated!

The following types were prefixed with __ to preserve valid JavaScript identifiers.
Clutter.__0 = Clutter.0
Clutter.__1 = Clutter.1
Clutter.__2 = Clutter.2
Clutter.__3 = Clutter.3
Clutter.__3270_AltCursor = Clutter.3270_AltCursor
Clutter.__3270_Attn = Clutter.3270_Attn
Clutter.__3270_BackTab = Clutter.3270_BackTab
Clutter.__3270_ChangeScreen = Clutter.3270_ChangeScreen
Clutter.__3270_Copy = Clutter.3270_Copy
Clutter.__3270_CursorBlink = Clutter.3270_CursorBlink
Clutter.__3270_CursorSelect = Clutter.3270_CursorSelect
Clutter.__3270_DeleteWord = Clutter.3270_DeleteWord
Clutter.__3270_Duplicate = Clutter.3270_Duplicate
Clutter.__3270_Enter = Clutter.3270_Enter
Clutter.__3270_EraseEOF = Clutter.3270_EraseEOF
Clutter.__3270_EraseInput = Clutter.3270_EraseInput
Clutter.__3270_ExSelect = Clutter.3270_ExSelect
Clutter.__3270_FieldMark = Clutter.3270_FieldMark
Clutter.__3270_Ident = Clutter.3270_Ident
Clutter.__3270_Jump = Clutter.3270_Jump
Clutter.__3270_KeyClick = Clutter.3270_KeyClick
Clutter.__3270_Left2 = Clutter.3270_Left2
Clutter.__3270_PA1 = Clutter.3270_PA1
Clutter.__3270_PA2 = Clutter.3270_PA2
Clutter.__3270_PA3 = Clutter.3270_PA3
Clutter.__3270_Play = Clutter.3270_Play
Clutter.__3270_PrintScreen = Clutter.3270_PrintScreen
Clutter.__3270_Quit = Clutter.3270_Quit
Clutter.__3270_Record = Clutter.3270_Record
Clutter.__3270_Reset = Clutter.3270_Reset
Clutter.__3270_Right2 = Clutter.3270_Right2
Clutter.__3270_Rule = Clutter.3270_Rule
Clutter.__3270_Setup = Clutter.3270_Setup
Clutter.__3270_Test = Clutter.3270_Test
Clutter.__4 = Clutter.4
Clutter.__5 = Clutter.5
Clutter.__6 = Clutter.6
Clutter.__7 = Clutter.7
Clutter.__8 = Clutter.8
Clutter.__9 = Clutter.9
Clutter.__function = Clutter.function

[08:42:04] Finished 'generate_gi_prefs' after 19 s
Generate .d.ts files for extensions: 
Loading docs.json...
Finding GIR files...
Resolving libraries...
Loading GIR files...
Adding generics...
Unknown type:  {
    "name": "gpu",
    "transfer-ownership": "none"
} 
Marking as unknown!
Unknown type:  {
    "name": "logical_monitor",
    "transfer-ownership": "none"
} 
Marking as unknown!
Injecting types...
>> Conflict in Text.position with Actor.position.
>> Conflict in Text.position with Actor.position.
Generated!

Failed to parse class: EmbeddedWindow in Shell.
Error: No single version found for unspecified dependency: Gtk.
    at GirNSRegistry.assertDefaultVersionOf (/mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/gir/registry.js:128:15)
    at GirNamespace.addImport (/mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/gir/namespace.js:170:45)
    at /mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/gir/class.js:615:28
    at Array.forEach (<anonymous>)
    at Function.fromXML (/mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/gir/class.js:609:34)
    at /mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/gir/namespace.js:327:132
    at Array.map (<anonymous>)
    at Function.fromXML (/mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/gir/namespace.js:327:102)
    at GirNSRegistry.load (/mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/gir/registry.js:142:52)
    at GirNSRegistry._internalLoad (/mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/gir/registry.js:184:37)
Error: No single version found for unspecified dependency: Gtk.
    at GirNSRegistry.assertDefaultVersionOf (/mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/gir/registry.js:128:15)
    at GirNamespace._getImport (/mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/gir/namespace.js:126:35)
    at GirNamespace.assertInstalledImport (/mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/gir/namespace.js:157:30)
    at resolveTypeIdentifier (/mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/gir/util.js:441:35)
    at /mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/validators/class.js:79:64
    at Array.filter (<anonymous>)
    at removeComplexFields (/mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/validators/class.js:59:31)
    at ClassVisitor.visitRecord (/mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/validators/class.js:146:61)
    at GirRecord.accept (/mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/gir/class.js:711:89)
    at GirNamespace.accept (/mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/@gi.ts/lib/dist/gir/namespace.js:109:46)
Failed to generate Shell 0.1!

[08:42:05] Finished 'generate_gi_ext' after 20 s
[08:42:05] Starting 'rename_gi'...
[08:42:06] Finished 'rename_gi' after 95 ms
[08:42:06] Starting '<anonymous>'...
[08:42:06] Finished '<anonymous>' after 643 μs
[08:42:06] Starting 'format'...
[08:42:07] Finished 'format' after 1.64 s
[08:42:07] Starting 'compile_ts'...
src/effect/clip_shadow_effect.ts(4,41): error TS2792: Cannot find module '@gi/Shell'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
src/effect/clip_shadow_effect.ts(24,12): error TS2339: Property 'add_glsl_snippet' does not exist on type '(Anonymous class)'.
src/effect/clip_shadow_effect.ts(29,12): error TS2339: Property 'get_pipeline' does not exist on type '(Anonymous class)'.
src/effect/linear_filter_effect.ts(5,41): error TS2792: Cannot find module '@gi/Shell'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
src/effect/linear_filter_effect.ts(11,12): error TS2339: Property 'add_glsl_snippet' does not exist on type '(Anonymous class)'.
src/effect/linear_filter_effect.ts(15,12): error TS2339: Property 'get_pipeline' does not exist on type '(Anonymous class)'.
src/effect/rounded_corners_effect.ts(4,41): error TS2792: Cannot find module '@gi/Shell'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
src/effect/rounded_corners_effect.ts(62,53): error TS2339: Property 'get_uniform_location' does not exist on type 'Effect'.
src/effect/rounded_corners_effect.ts(68,12): error TS2339: Property 'add_glsl_snippet' does not exist on type 'Effect'.
src/effect/rounded_corners_effect.ts(74,12): error TS2339: Property 'get_pipeline' does not exist on type 'Effect'.
src/effect/rounded_corners_effect.ts(121,28): error TS2339: Property 'actor' does not exist on type 'Effect'.
src/effect/rounded_corners_effect.ts(148,12): error TS2339: Property 'set_uniform_float' does not exist on type 'Effect'.
src/effect/rounded_corners_effect.ts(149,12): error TS2339: Property 'set_uniform_float' does not exist on type 'Effect'.
src/effect/rounded_corners_effect.ts(150,12): error TS2339: Property 'set_uniform_float' does not exist on type 'Effect'.
src/effect/rounded_corners_effect.ts(151,12): error TS2339: Property 'set_uniform_float' does not exist on type 'Effect'.
src/effect/rounded_corners_effect.ts(152,12): error TS2339: Property 'set_uniform_float' does not exist on type 'Effect'.
src/effect/rounded_corners_effect.ts(153,12): error TS2339: Property 'set_uniform_float' does not exist on type 'Effect'.
src/effect/rounded_corners_effect.ts(154,12): error TS2339: Property 'set_uniform_float' does not exist on type 'Effect'.
src/effect/rounded_corners_effect.ts(155,12): error TS2339: Property 'set_uniform_float' does not exist on type 'Effect'.
src/effect/rounded_corners_effect.ts(156,12): error TS2339: Property 'queue_repaint' does not exist on type 'Effect'.
src/extension.ts(123,37): error TS2339: Property 'window_container' does not exist on type 'WindowPreview'.
src/extension.ts(127,32): error TS2345: Argument of type 'RegisteredPrototype<(Anonymous class), { [key: string]: ParamSpec<unknown>; }, unknown[]>' is not assignable to parameter of type 'Effect'.
  Type 'Properties<(Anonymous class), SnakeToCamel<{ [key: string]: ParamSpec<unknown>; }> & SnakeToUnderscore<{ [key: string]: ParamSpec<unknown>; }>> & (Anonymous class)' is missing the following properties from type 'Effect': _init, queue_repaint, vfunc_modify_paint_volume, vfunc_paint, and 51 more.
src/extension.ts(134,12): error TS2339: Property 'insert_child_below' does not exist on type 'WindowPreview'.
src/extension.ts(152,9): error TS18046: 'rounded_effect_of_window_actor.set_enabled' is of type 'unknown'.
src/extension.ts(155,9): error TS18047: 'first_child' is possibly 'null'.
src/extension.ts(155,49): error TS2345: Argument of type 'RegisteredPrototype<Effect, { [key: string]: ParamSpec<unknown>; }, unknown[]>' is not assignable to parameter of type 'Effect'.
src/extension.ts(160,20): error TS2769: No overload matches this call.
  Overload 1 of 2, '(source: Object, signal: "notify", callback: (_source: Object, pspec: ParamSpec<unknown>) => void): void', gave the following error.
    Argument of type 'WindowPreview' is not assignable to parameter of type 'Object'.
      Type 'WindowPreview' is missing the following properties from type 'Object': _init, g_type_instance, connect, connect_after, and 34 more.
  Overload 2 of 2, '(source: Object, args_0: string, args_1: (_: unknown[]) => unknown): void', gave the following error.
    Argument of type 'WindowPreview' is not assignable to parameter of type 'Object'.
src/extension.ts(170,31): error TS2339: Property 'window_container' does not exist on type 'WindowPreview'.
src/extension.ts(200,18): error TS2769: No overload matches this call.
  Overload 1 of 2, '(source: Object, signal: "notify", callback: (_source: Object, pspec: ParamSpec<unknown>) => void): void', gave the following error.
    Argument of type 'WindowPreview' is not assignable to parameter of type 'Object'.
  Overload 2 of 2, '(source: Object, args_0: string, args_1: (_: unknown[]) => unknown): void', gave the following error.
    Argument of type 'WindowPreview' is not assignable to parameter of type 'Object'.
src/extension.ts(208,11): error TS18046: 'rounded_effect_of_window_actor.set_enabled' is of type 'unknown'.
src/extension.ts(211,27): error TS2345: Argument of type 'WindowPreview' is not assignable to parameter of type 'Object'.
src/extension.ts(383,32): error TS2339: Property 'window_container' does not exist on type 'WindowPreview'.
src/extension.ts(384,32): error TS2339: Property 'get_allocation_box' does not exist on type 'WindowPreview'.
src/manager/effect_manager.ts(17,28): error TS2792: Cannot find module '@gi/Shell'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?
src/manager/effect_manager.ts(121,45): error TS7006: Parameter 'actor' implicitly has an 'any' type.
src/manager/effect_manager.ts(133,43): error TS7006: Parameter 'actor' implicitly has an 'any' type.
src/manager/effect_manager.ts(151,33): error TS2769: No overload matches this call.
  Overload 1 of 2, '(source: Object, signal: "notify", callback: (_source: Object, pspec: ParamSpec<unknown>) => void): void', gave the following error.
    Argument of type 'ShapedTexture | null' is not assignable to parameter of type 'Object'.
      Type 'null' is not assignable to type 'Object'.
  Overload 2 of 2, '(source: Object, args_0: string, args_1: (_: unknown[]) => unknown): void', gave the following error.
    Argument of type 'ShapedTexture | null' is not assignable to parameter of type 'Object'.
      Type 'null' is not assignable to type 'Object'.
src/manager/effect_manager.ts(217,40): error TS2345: Argument of type 'ShapedTexture | null' is not assignable to parameter of type 'Object'.
  Type 'null' is not assignable to type 'Object'.
src/manager/rounded_corners_manager.ts(51,7): error TS2345: Argument of type 'RegisteredPrototype<Effect, { [key: string]: ParamSpec<unknown>; }, unknown[]>' is not assignable to parameter of type 'Effect'.
  Type 'Properties<Effect, SnakeToCamel<{ [key: string]: ParamSpec<unknown>; }> & SnakeToUnderscore<{ [key: string]: ParamSpec<unknown>; }>> & Effect' is missing the following properties from type 'Effect': _init, queue_repaint, vfunc_modify_paint_volume, vfunc_paint, and 51 more.
src/manager/rounded_corners_manager.ts(326,7): error TS2345: Argument of type 'RegisteredPrototype<(Anonymous class), { [key: string]: ParamSpec<unknown>; }, unknown[]>' is not assignable to parameter of type 'Effect'.
  Type 'Properties<(Anonymous class), SnakeToCamel<{ [key: string]: ParamSpec<unknown>; }> & SnakeToUnderscore<{ [key: string]: ParamSpec<unknown>; }>> & (Anonymous class)' is missing the following properties from type 'Effect': _init, queue_repaint, vfunc_modify_paint_volume, vfunc_paint, and 51 more.
src/manager/rounded_corners_manager.ts(465,43): error TS7006: Parameter 'actor' implicitly has an 'any' type.
src/preferences/widgets/edit_shadow_window.ts(139,29): error TS2554: Expected 2 arguments, but got 1.
src/preferences/widgets/edit_shadow_window.ts(142,27): error TS2554: Expected 2 arguments, but got 1.
TypeScript: 43 semantic errors
TypeScript: emit succeeded (with errors)
[08:42:09] 'compile_ts' errored after 2.01 s
[08:42:09] Error: TypeScript: Compilation failed
    at Output.mightFinish (/mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/gulp-typescript/release/output.js:131:43)
    at /mnt/storage/AUR/gnome-shell-extension-rounded-window-corners-git/src/rounded-window-corners/node_modules/gulp-typescript/release/output.js:44:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[08:42:09] 'build' errored after 24 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

</details>

**Comment by yilozt** [comment]
Thanks to point out this information, I have found the TypeScript Definitions files which need has been uploaded to npm:

https://www.npmjs.com/package/@gi-types/shell0
https://www.npmjs.com/package/@gi-types/meta10

Now this extensions needn't generate those file manually.

**Comment by yochananmarqos** [comment]
Thanks, it's working now. :+1:
